version: '3.8'

services:
  rustcompiler:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - RUST_LOG=info
      - CORS_ALLOWED_ORIGIN=*
    restart: unless-stopped 